### ISSUE TITLE
template key breaks on Windows x64

### ISSUE THREAD

**Issue by ghost** [isaacs/templar#8]
I am running Win 7 x64 and the key being created using the Stats object is always '0:0'. 

I am not sure whether this is an environment issue on my end since I _think_ these are stats on the file location but maybe Windows is simply not reporting it? What would Isaac do ? :)

For reference, the key gen is here:

``` js

function loadFile_ (file, st) {
  st.contents = fs.readFileSync(file, 'utf8')
  st.key = st.dev + ':' + st.ino
  return st
}

```

**Comment by isaacs** [comment]
Yeah.  That sucks.  Maybe it should use the filename for windows instead.
